### ISSUE TITLE
Notice a player some seconds(!) earlier before duck soars

### ISSUE THREAD

**Issue by MAGICCC** [theworm4002/IRC_DuckHunt#1]
When an user have a ducks detector the notice when the next duck soars is send at the same time than the duck soars. There's no advantage for having this item. Maybe adding a sleep of some seconds so the user is prepared for shooting the duck

https://github.com/theworm4002/IRC_DuckHunt/blob/89f65aeba184c1bb1cea7ce0d134df7d2ccea4b1/Duck_Hunt.tcl#L334

**Comment by theworm4002** [comment]
hmm, yeah that is useless. I will think about this some.
